Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -65,6 +65,14 @@ pipeline {
             passwordVariable: 'DOCKER_PASS'
           )]) {
             sh '''
+               echo "PWD:"
+                       pwd
+               echo "FILES:"
+                   ls -ltr
+               echo "TARGET:"
+                   ls -ltr target || echo "❌ target folder missing"
+                 '''
+
               docker build -t $IMAGE_NAME:$IMAGE_TAG .
               echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
               docker push $IMAGE_NAME:$IMAGE_TAG
